version: "3.9"

services:
  app:
    image: ghcr.io/gabe565/castsponsorskip
    environment:
      CSS_PAUSED_INTERVAL: 1m
      CSS_PLAYING_INTERVAL: 1s
      CSS_CATEGORIES: sponsor
    network_mode: host
    restart: always
    volumes:
      - "/etc/localtime:/etc/localtime:ro" # Use host's localtime, mounted read-only
